using Autodesk.Revit.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RevitGuide.Helpers;
namespace RevitGuide.Commands
{
    public class RvtCommandManager
    {
/*        public static List<RvtCommand> _allRvtCommands;
        public static List<RvtCommand> AllRvtCommands
        {
            get
            {
                if (_allRvtCommands == null)
                {
                    _allRvtCommands = GetAllRvtCommands();
                }
                return _allRvtCommands;
            }
        }*/

/*        private static List<RvtCommand> GetAllRvtCommands()
        {
            for
            List<RvtCommand> rvtCommands = new List<RvtCommand>();
            foreach (PostableCommand command in mockCommandList)
            {
                
                rvtCommands.Add(new RvtCommand(command));
            }
            return rvtCommands;
        }*/
    }
}
